version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - db
  redis_exporter:
    image: oliver006/redis_exporter:latest
    command: ["--redis.addr=redis:6379"]
    ports:
      - "9121:9121"
    depends_on:
      - redis

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - METRICS_ADDR=:9090
    depends_on:
      - redis
      - db
    ports:
      - "9091:9090"

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  ml:
    build:
      context: ../ml
      dockerfile: Dockerfile
    depends_on:
      - db

  grafana:
    image: grafana/grafana:9.5.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

