FROM golang:1.21-alpine AS builder
RUN apk add --no-cache git
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY aisstreamer/ ./aisstreamer/
RUN go build -o /bin/aisstreamer ./aisstreamer/

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/aisstreamer /bin/aisstreamer
ENTRYPOINT ["/bin/aisstreamer"]
