apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: portscope
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        static_configs:
          - targets: ['api:8080', 'consumer:9090']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
